packages:
  - .

saveExact: true
minimumReleaseAge: 10080
minimumReleaseAgeExcludePrune: true

allowBuilds:
  esbuild: true
  lefthook: true
  msw: false
  unrs-resolver: true

overrides:
  postcss: 8.5.22
  sharp: 0.35.3
